### ISSUE TITLE
Add support for displaying plugins in docked panels within the GMDC interface like on GM UWP and mobile apps

### ISSUE THREAD

**Issue by OuchMyFaceyHole** [alexdillon/GroupMeClient#124]
Some plugins, like the giphy plugin, could be displayed in an inline-docked panel underneath the message composition bar.

**Comment by alexdillon** [comment]
This would require some pretty substantial revamp of the client API but should be possible

**Comment by alexdillon** [comment]
This discussion is being continued in the megathread #139. Please feel free to continue the discussion there!
