### ISSUE TITLE
Feedback about using toast notifications in Win32 apps

### ISSUE THREAD

**Issue by andrewleader** [alexdillon/GroupMeClient#129]
Hi @alexdillon, my name is Andrew Leader, I work at Microsoft in the Windows Developer Platform team. We’re looking into how we can make toast notifications for Win32 apps easier to use.

I saw your app and noticed you utilize notifications. Would you be able to share a bit about your experience implementing toast notifications in your app?

•	Summarize the general process you went through while implementing notifications (partially to help you recall all the steps you went through)
•	What was difficult?
•	What was easy/what did you enjoy?
•	Where did you spend more time than you felt you wanted to?
•	If you could have us change anything, what would you have us change?
•	What did you think of how toast activations (clicks) are handled? Is there a different way you would prefer to receive activations?

We’re seeking honest feedback, please do not be worried about insulting us or being too harsh, we want the truth so that we can make the lives of developers better 😊

I look forward to your response and appreciate your time! I’m also happy to schedule a call if you’d like to chat over video.

Thanks!
Andrew – PM on the Windows Developer Platform

**Comment by alexdillon** [comment]
Hey @andrewleader !
Sorry for the delayed response - I've been tied up with work and finishing some better documentation on these repos. If it's okay with you, I've transferred this issue out of the GroupMeClientAvalonia repo and into the main GroupMeClient repo. All of the original development work was done here, and later (partially) ported over to the Avalonia repo. There should be a lot more relevant pull-requests and commits regarding toast notifications that I can link back to. This repo is also quite a bit more feature complete with notification support than GroupMeClientAvalonia. 

Let me take a look through my notes and see what feedback I can come up with. I'll be glad to share any information I can. I appreciate you reaching out!

Thanks!
Alex
