### ISSUE TITLE
Add support for locally hiding messages

### ISSUE THREAD

**Issue by arvinddraffen** [alexdillon/GroupMeClient#130]
This would act similarly to the "Hide Message" feature on many apps, where a message can be hidden from a group or DM thread locally. One user hiding a message would not affect the ability of any other users to view or access the message from their accounts.

**Comment by alexdillon** [comment]
This seems reasonable to add in. Are you looking to have it completely hide the message where it is essentially invisible in a thread, or just collapse it and leave a placeholder showing "hidden message" or something?

**Comment by arvinddraffen** [comment]
I feel like true hiding is better, and would be more in line with what the official GroupMe app and other messengers offer in their clients. Collapsing could be a useful expansion of this by not requiring needing to navigate to a separate page in order to see hidden messages and unhide them, but for a "hiding" feature I feel true hiding better fits in.

**Comment by alexdillon** [comment]
Thanks for the idea! This sounds great. True hiding should be available in the GMDC 29 release. We can look into collapsible messages for a future release.
